/**
 * 
 */
package com.lixiaodao.rpc.core.codec.impl;

import org.apache.zookeeper.server.quorum.QuorumCnxManager.Message;

import com.lixiaodao.rpc.core.codec.RpcEncoder;
public class ProtocolBufEncoder implements RpcEncoder {

	@Override
	public byte[] encode(Object object) throws Exception {
		if (!(object instanceof Message)) {
			throw new Exception(
					"Send object is not type of com.google.protobuf.Message,pls sure the object is generated by pb,object is: "
							+ object);
		}
		com.google.protobuf.Message message = (com.google.protobuf.Message) object;
		return message.toByteArray();
	}

}
